blueprint:
  name: "💬 Zustandsbenachrichtigung (Blueprint v1.5.1)"
  description: >
    Benachrichtigt dich, wenn ausgewählte Entitäten einen Zielzustand erreichen
    (oder numerisch darüber/darunter liegen). Optional periodische Wiederholung,
    Aktionen und Bedingungen. Unterstützt globale Listener für Notification-Aktionen.
    🧩 v1.5.1: Korrektur der Gruppenverarbeitung, iOS-Fallback für non-critical Levels,
    Auto-Delete (clear_notification) verbessert.
  source_url: https://github.com/michaelf988/entity_state_notification/blob/main/entity_state_notification.yaml
  domain: automation

  input:
    sensor_section:
      name: Entitäten / Gleichheitsvergleich
      icon: mdi:equal-box
      collapsed: true
      input:
        input_entities:
          name: "🖲️ Beobachtete Entitäten"
          description: >
            Entitäten, die die Benachrichtigung auslösen.
          default: []
          selector:
            entity:
              multiple: true

        input_entity_states:
          name: "🟢 Zielzustände"
          description: >
            Zustände, die die Automatisierung auslösen.
          default: []
          selector:
            text:
              multiple: true

        input_entity_state_duration:
          name: "⏲️ Verweilzeit im Zielzustand"
          description: >
            Dauer, die die Entität im Zielzustand sein muss.
          default:
            hours: 0
            minutes: 0
            seconds: 2
          selector:
            duration:

    state_multi_section:
      name: Mehrere Zustände (indexbasiert)
      icon: mdi:format-list-bulleted
      collapsed: true
      input:
        ms_entities:
          name: "🖲️ Entitäten (Mehrfach)"
          description: >
            Liste der zu überwachenden Entitäten. Die Position entspricht den
            Zielzuständen in der nächsten Liste.
          default: []
          selector:
            entity:
              multiple: true

        ms_target_states:
          name: "🟢 Zielzustände je Entität"
          description: >
            Für jede Entität ein Eintrag. Mehrere Zustände pro Eintrag mit | oder , trennen
            (z. B. "on|open", "home,available").
          default: []
          selector:
            text:
              multiple: true

    numeric_multi_section:
      name: Mehrere numerische Vergleiche (indexbasiert)
      icon: mdi:view-list
      collapsed: true
      input:
        nm_entities:
          name: "🖲️ Numerische Entitäten (Mehrfach)"
          description: >
            Liste der zu überwachenden numerischen Entitäten. Die Position
            entspricht dem passenden Schwellwert unten.
          default: []
          selector:
            entity:
              multiple: true

        nm_thresholds:
          name: "🟢 Schwellwerte je Entität (mit Operator)"
          description: >
            Pro Entität genau ein Eintrag mit Operator **<** oder **>** und Zahl.
            Beispiele: `>5`, `<1,2`, `> 12.3`. Dezimal-Komma wird unterstützt.
          default: []
          selector:
            text:
              multiple: true

        input_numeric_entity_state_duration:
          name: "⏲️ Verweilzeit (Multi-Numerik)"
          description: >
            Dauer, die die Bedingung (> oder <) ununterbrochen erfüllt sein muss,
            bevor benachrichtigt wird. 0 = sofort.
          default:
            hours: 0
            minutes: 0
            seconds: 2
          selector:
            duration:

    notifcation_section:
      name: Benachrichtigung
      icon: mdi:chat
      collapsed: true
      input:
        input_notify_devices:
          name: "📱 Gerät(e) benachrichtigen"
          description: >
            Geräte/Gruppen, die die Benachrichtigung erhalten.
          default: []
          selector:
            device:
              multiple: true
              filter:
                integration: mobile_app

        input_notify_groups:
          name: "🫂 Benachrichtigungsgruppen"
          description: >
            Namen von Notification-Gruppen **ohne 'notify.'** angeben
            (z. B. `MF_Notify_Group`).
          default: []
          selector:
            text:
              multiple: true

        input_title:
          name: "📕 Titel"
          description: >
            Titel der Benachrichtigung.
          default: "{{ entity_name }} ist {{ new_state }}"

        input_message:
          name: "💬 Nachricht"
          description: >
            Text der Benachrichtigung.
          default: "Hinweis: {{ entity_name }} ist {{ new_state }}"

        input_persistent_notification:
          name: "🪨 Persistente Benachrichtigung"
          description: >
            Kann nicht weggewischt werden; verschwindet erst,
            wenn die Entität den Zielzustand verlässt.
          default: false
          selector:
            boolean:

        input_notification_auto_delete:
          name: "❌ Auto-Schließen"
          description: >
            Benachrichtigungen automatisch schließen,
            wenn die Zielzustands-Bedingung nicht mehr gilt.
          default: true
          selector:
            boolean:

        input_ha_notification:
          name: "🏠 HA-Benachrichtigung (Frontend)"
          description: >
            Erstellt zusätzlich eine persistente Benachrichtigung im HA-Frontend.
          default: false
          selector:
            boolean:

        input_interruption_level:
          name: "⛔ Interruption Level (iOS)"
          description: >
            Einstellen, wie „dringlich“ die Benachrichtigung ist.
          default: "active"
          selector:
            select:
              options:
                - passive
                - active
                - time-sensitive
                - critical

        input_custom_tag:
          name: "🏷️ Tag"
          description: >
            Eindeutiger Tag für die Benachrichtigung (für globalen Listener empfohlen).
          default: ""
          selector:
            text:

        input_ios_sound:
          name: "🔊 iOS Sound"
          description: >
            Name des Sounds (z. B. default oder <Soundname>).
          default: "default"
          selector:
            text:

        input_critical_volume:
          name: "🔊 Kritische Lautstärke (iOS)"
          description: >
            Nur bei *Interruption Level* = **critical**. Bereich 0.0–1.0 (0–100 %).
          default: 1.0
          selector:
            number:
              min: 0
              max: 1
              step: 0.05

        input_group_text:
          name: "📑 Group"
          description: >
            Gruppiere Benachrichtigungen über diese Kennung.
          default: ""
          selector:
            text:

    actionable_section:
      name: Actionable Notifications
      icon: mdi:gesture-tap-button
      collapsed: true
      input:
        input_action_timeout:
          name: "⏳ Antwort-Timeout (nur Inline-Warten)"
          default:
            seconds: 60
          selector:
            duration:
        input_action1_enabled:
          name: "Aktion 1 aktivieren"
          default: false
          selector:
            boolean:
        input_action1_title:
          name: "Titel Aktion 1"
          default: "Aktion 1"
          selector:
            text:
        input_action1_type:
          name: "Typ Aktion 1"
          default: "uri"
          selector:
            select:
              options:
                - uri
                - ha_action
        input_action1_uri:
          name: "URI Aktion 1 (falls Typ=uri)"
          default: ""
          selector:
            text:
        input_action1_destructive:
          name: "Destructive (Aktion 1)"
          default: false
          selector:
            boolean:
        input_action1_ha_action:
          name: "HA-Aktion bei Antwort (Aktion 1, falls Typ=ha_action)"
          default: []
          selector:
            action: {}
        input_action2_enabled:
          name: "Aktion 2 aktivieren"
          default: false
          selector:
            boolean:
        input_action2_title:
          name: "Titel Aktion 2"
          default: "Aktion 2"
          selector:
            text:
        input_action2_type:
          name: "Typ Aktion 2"
          default: "uri"
          selector:
            select:
              options:
                - uri
                - ha_action
        input_action2_uri:
          name: "URI Aktion 2 (falls Typ=uri)"
          default: ""
          selector:
            text:
        input_action2_destructive:
          name: "Destructive (Aktion 2)"
          default: false
          selector:
            boolean:
        input_action2_ha_action:
          name: "HA-Aktion bei Antwort (Aktion 2, falls Typ=ha_action)"
          default: []
          selector:
            action: {}
        input_action3_enabled:
          name: "Aktion 3 aktivieren"
          default: false
          selector:
            boolean:
        input_action3_title:
          name: "Titel Aktion 3"
          default: "Aktion 3"
          selector:
            text:
        input_action3_type:
          name: "Typ Aktion 3"
          default: "uri"
          selector:
            select:
              options:
                - uri
                - ha_action
        input_action3_uri:
          name: "URI Aktion 3 (falls Typ=uri)"
          default: ""
          selector:
            text:
        input_action3_destructive:
          name: "Destructive (Aktion 3)"
          default: false
          selector:
            boolean:
        input_action3_ha_action:
          name: "HA-Aktion bei Antwort (Aktion 3, falls Typ=ha_action)"
          default: []
          selector:
            action: {}

    peridodic_notification_section:
      name: Periodische Benachrichtigungen
      icon: mdi:refresh
      collapsed: true
      input:
        input_period:
          name: "🔄 Wiederholung"
          default:
            seconds: 0
          selector:
            duration:
        input_stop_button_text:
          name: "💬 Stopp-Button-Text"
          default: "Benachrichtigungen anhalten"
        input_stop_turn_off_automation:
          name: "Automation bei Stopp deaktivieren"
          default: false
          selector:
            boolean:

    custom_section:
      name: Eigene Aktionen / Bedingungen
      icon: mdi:cog
      collapsed: true
      input:
        input_custom_condition:
          name: "❌ Bedingungen"
          default: []
          selector:
            condition:
        input_custom_action_on:
          name: "🎬 Eigene Aktion bei Eintritt"
          default: []
          selector:
            action: {}
        input_custom_action_off:
          name: "🎬 Eigene Aktion bei Verlassen"
          default: []
          selector:
            action: {}

trigger_variables:
  input_entities: !input input_entities

trigger:
  - id: state_on
    trigger: state
    entity_id: !input input_entities
    to: !input input_entity_states
    for: !input input_entity_state_duration
  - id: state_off
    trigger: state
    entity_id: !input input_entities
    not_to: !input input_entity_states
  - id: ms_on
    trigger: state
    entity_id: !input ms_entities
    for: !input input_entity_state_duration
  - id: ms_off
    trigger: state
    entity_id: !input ms_entities
  - id: num_multi_on
    trigger: state
    entity_id: !input nm_entities
  - id: num_multi_off
    trigger: state
    entity_id: !input nm_entities
  - id: period
    trigger: event
    event_type: esn_event
    event_data:
      automation: "{{ this.entity_id }}"
  - id: action_event
    trigger: event
    event_type: mobile_app_notification_action

variables:
  input_notify_devices: !input input_notify_devices
  input_notify_groups: !input input_notify_groups
  input_interruption_level: !input input_interruption_level
  input_ios_sound: !input input_ios_sound
  input_critical_volume: !input input_critical_volume
  input_group_text: !input input_group_text
  input_custom_tag: !input input_custom_tag
  input_persistent_notification: !input input_persistent_notification
  input_notification_auto_delete: !input input_notification_auto_delete
  input_title: !input input_title
  input_message: !input input_message
  entity: "{{ trigger.entity_id }}"
  entity_name: "{{ state_attr(entity, 'friendly_name') }}"
  new_state: "{{ trigger.to_state.state }}"
  tag: >
    {% if (input_custom_tag|string)|length > 0 %}
      {{ input_custom_tag }}
    {% else %}
      {{ this.entity_id.split('.')[1] ~ '_' ~ entity.split('.')[1] }}
    {% endif %}
  notify_devices: "{{ input_notify_devices | map('device_attr', 'name') | list }}"
  # --- Fix 1: Korrekte Gruppenverarbeitung ---
  notify: >
    {% set result = namespace(r=[]) %}
    {% for device in notify_devices %}
      {% set result.r = result.r + ['notify.mobile_app_' + device | slugify] %}
    {% endfor %}
    {% for group in input_notify_groups %}
      {% set result.r = result.r + ['notify.' + group] %}
    {% endfor %}
    {{ result.r }}

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ (not (trigger.to_state.state in input_entity_states)) and input_notification_auto_delete }}
      - condition: template
        value_template: >
          {{ trigger.to_state.state in input_entity_states }}

action:
  - choose:

      # --- Fix 2: Auto-Delete-Zweig ---
      - conditions:
          - condition: template
            value_template: >
              {{ (not (trigger.to_state.state in input_entity_states)) and input_notification_auto_delete }}
        sequence:
          - repeat:
              count: "{{ notify | count | int }}"
              sequence:
                - variables:
                    idx: "{{ repeat.index-1 }}"
                    notify_target: "{{ notify[idx] }}"
                - action: "{{ notify_target }}"
                  data:
                    message: clear_notification
                    data:
                      tag: "{{ tag }}"
                      ttl: 0
                      priority: high

      # --- Hauptbenachrichtigung mit Fallback ---
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.to_state.state in input_entity_states }}
        sequence:
          - repeat:
              count: "{{ notify | count | int }}"
              sequence:
                - variables:
                    idx: "{{ repeat.index-1 }}"
                    notify_target: "{{ notify[idx] }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ input_interruption_level == 'critical' }}"
                      sequence:
                        - action: "{{ notify_target }}"
                          data:
                            title: "{{ input_title }}"
                            message: "{{ input_message }}"
                            data:
                              ttl: 0
                              priority: high
                              tag: "{{ tag }}"
                              persistent: "{{ input_persistent_notification }}"
                              sticky: "{{ input_persistent_notification }}"
                              group: "{{ input_group_text }}"
                              push:
                                interruption-level: critical
                                sound:
                                  name: "{{ input_ios_sound }}"
                                  critical: 1
                                  volume: "{{ input_critical_volume }}"
                              actions: []
                  # --- Fix 3: Standard-Fallback ---
                  default:
                    - action: "{{ notify_target }}"
                      data:
                        title: "{{ input_title }}"
                        message: "{{ input_message }}"
                        data:
                          tag: "{{ tag }}"
                          group: "{{ input_group_text }}"
                          push:
                            interruption-level: "{{ input_interruption_level }}"
                          actions: []

mode: restart
